# Use official Nginx base image
FROM public.ecr.aws/nginx/nginx:latest

COPY ./index.html /usr/share/nginx/html/

# Expose default Nginx port
EXPOSE 80

# Start Nginx in foreground (so container doesn't exit)
CMD ["nginx", "-g", "daemon off;"]
